# Disable problematic IDE scripts
kotlin.internal.doctor.enabled=false
kotlin.mpp.doctor.enabled=false

# Project Settings
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.jvm.version.check=false
android.useAndroidX=true
kotlin.code.style=official

# Force Java 17 for the build
org.gradle.java.home=/Library/Java/JavaVirtualMachines/openjdk-17.jdk/Contents/Home
