# Disable problematic IDE scripts
kotlin.internal.doctor.enabled=false
kotlin.mpp.doctor.enabled=false

# Project Settings
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.jvm.version.check=false
android.useAndroidX=true
kotlin.code.style=official

# Allow Gradle to download missing JDKs (like a package manager)
org.gradle.java.installations.auto-download=true
org.gradle.java.installations.auto-detect=true

# Bootstrap JDK (Uses the one bundled with Android Studio)
org.gradle.java.home=/Applications/Android Studio.app/Contents/jbr/Contents/Home
