package com.bracketcove.graphsudoku.persistence

import android.content.Context
import androidx.datastore.core.CorruptionException
import androidx.datastore.core.DataStore
import androidx.datastore.core.Serializer
import androidx.datastore.dataStore
import com.bracketcove.graphsudoku.GameSettings
import com.bracketcove.graphsudoku.Statistics
import com.google.protobuf.InvalidProtocolBufferException
import java.io.InputStream
import java.io.OutputStream

// creating a datastore object, takes the gamesettings java class generated by the protocol buffer
// to create a reference we can then use to store or retrieve our protocol buffer
internal val Context.settingsDataStore: DataStore<GameSettings> by dataStore (
    fileName = "game_settings.pb",
    serializer = GameSettingsSerializer
)

// helps us to read and write from input streams
private object GameSettingsSerializer : Serializer<GameSettings> {
    override suspend fun readFrom(input: InputStream): GameSettings {
        try {
            return GameSettings.parseFrom(input)
        } catch (exception: InvalidProtocolBufferException) {
            throw CorruptionException("Cannot read proto.", exception)
        }
    }

    override suspend fun writeTo(t: GameSettings, output: OutputStream) = t.writeTo(output)

    override val defaultValue: GameSettings
        get() = GameSettings.getDefaultInstance()
}


internal val Context.statsDataStore: DataStore<Statistics> by dataStore(
    fileName = "user_statistics.pb",
    serializer =  StatisticsSerializer
)

private object StatisticsSerializer : Serializer<Statistics> {
    override val defaultValue: Statistics = Statistics.getDefaultInstance()

    override suspend fun readFrom(input: InputStream): Statistics {
        try {
            return Statistics.parseFrom(input)
        } catch (exception: InvalidProtocolBufferException) {
            throw CorruptionException("Cannot read proto.", exception)
        }
    }

    override suspend fun writeTo(
        t: Statistics,
        output: OutputStream
    ) = t.writeTo(output)

}